var searchData=
[
  ['readme_2emd_0',['readme.md',['../_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)']]],
  ['ready_20to_20use_20with_20bootstrap_20and_20foundation_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20view_20the_20collection_20a_1',['ready to use with bootstrap and foundation a href https: github com iconic open iconic view the collection a',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md0',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md14',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;']]],
  ['reference_20a_20sections_2',['reference a sections',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md3',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md17',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.']]],
  ['registerasync_3',['registerasync',['../class_blazor_wasm_1_1_services_1_1_http_1_1_jwt_auth_service.html#a5e5f2bb4e78c7fcc172ecdd669a9d3b1',1,'BlazorWasm.Services.Http.JwtAuthService.RegisterAsync()'],['../interface_blazor_wasm_1_1_services_1_1_i_auth_service.html#a14f8e44a06ff19f0df91b2286a0adb2b',1,'BlazorWasm.Services.IAuthService.RegisterAsync()'],['../class_blazor_wasm_1_1_services_1_1_http_1_1_jwt_auth_service.html#a0d57124f1227ce6491229e58825aaf94',1,'BlazorWasm.Services.Http.JwtAuthService.RegisterAsync()'],['../interface_blazor_wasm_1_1_services_1_1_i_auth_service.html#a49bb437885269e52231455b483474d9e',1,'BlazorWasm.Services.IAuthService.RegisterAsync()']]],
  ['registeruser_4',['registeruser',['../class_web_a_p_i_1_1_services_1_1_auth_service.html#ae549647210b7bd57493aac22c18a01b4',1,'WebAPI.Services.AuthService.RegisterUser()'],['../interface_web_a_p_i_1_1_services_1_1_i_auth_service.html#a297eabf174b2bc9e116966fc94c3a6f5',1,'WebAPI.Services.IAuthService.RegisterUser()'],['../class_web_a_p_i_1_1_services_1_1_auth_service.html#ae549647210b7bd57493aac22c18a01b4',1,'WebAPI.Services.AuthService.RegisterUser()'],['../interface_web_a_p_i_1_1_services_1_1_i_auth_service.html#a297eabf174b2bc9e116966fc94c3a6f5',1,'WebAPI.Services.IAuthService.RegisterUser()']]],
  ['run_5',['run',['../folder_2_web_a_p_i_2_program_8cs.html#aaa3dbf02e269c3ef7e8546d290c6b3dd',1,'Run():&#160;Program.cs'],['../_web_a_p_i_2_program_8cs.html#aaa3dbf02e269c3ef7e8546d290c6b3dd',1,'Run():&#160;Program.cs']]]
];
