var searchData=
[
  ['s_20icon_20font_0',['s icon font',['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md21',1,'Using Open Iconic&apos;s Icon Font...'],['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md7',1,'Using Open Iconic&apos;s Icon Font...']]],
  ['s_20in_20open_20iconic_1',['s in open iconic',['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md15',1,'What&apos;s in Open Iconic?'],['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md1',1,'What&apos;s in Open Iconic?']]],
  ['s_20svg_20sprite_2',['s svg sprite',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md6',1,'Using Open Iconic&apos;s SVG Sprite'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md20',1,'Using Open Iconic&apos;s SVG Sprite']]],
  ['s_20svgs_3',['s svgs',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md5',1,'Using Open Iconic&apos;s SVGs'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md19',1,'Using Open Iconic&apos;s SVGs']]],
  ['samples_20and_20everything_20else_20you_20need_20to_20get_20started_20with_20open_20iconic_20check_20out_20our_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20icons_20a_20and_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20reference_20a_20sections_4',['samples and everything else you need to get started with open iconic check out our a href https: github com iconic open iconic icons a and a href https: github com iconic open iconic reference a sections',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md3',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md17',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.']]],
  ['savechanges_5',['SaveChanges',['../class_file_data_1_1_file_context.html#ad1d94fa4996c44109f6883a8923eed35',1,'FileData::FileContext']]],
  ['score_6',['Score',['../class_domain_1_1_models_1_1_post.html#a55e04333ff6e053ce209d124bbcfd966',1,'Domain::Models::Post']]],
  ['searchpostparametersdto_7',['searchpostparametersdto',['../class_domain_1_1_d_t_os_1_1_search_post_parameters_dto.html#a8a5dbca90b0a506fd40d16cf860dd556',1,'Domain.DTOs.SearchPostParametersDto.SearchPostParametersDto()'],['../class_domain_1_1_d_t_os_1_1_search_post_parameters_dto.html',1,'Domain.DTOs.SearchPostParametersDto']]],
  ['searchpostparametersdto_2ecs_8',['SearchPostParametersDto.cs',['../_search_post_parameters_dto_8cs.html',1,'']]],
  ['searchuserparametersdto_9',['searchuserparametersdto',['../class_domain_1_1_d_t_os_1_1_search_user_parameters_dto.html',1,'Domain.DTOs.SearchUserParametersDto'],['../class_domain_1_1_d_t_os_1_1_search_user_parameters_dto.html#a89e827ce1aaae748d15bc4f830e5a64c',1,'Domain.DTOs.SearchUserParametersDto.SearchUserParametersDto()']]],
  ['searchuserparametersdto_2ecs_10',['SearchUserParametersDto.cs',['../_search_user_parameters_dto_8cs.html',1,'']]],
  ['sections_11',['sections',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md3',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md17',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.']]],
  ['shared_12',['Shared',['../namespace_shared.html',1,'']]],
  ['sibling_20of_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20iconic_20a_20it_20is_20a_20hyper_20legible_20collection_20of_20223_20icons_20with_20a_20tiny_20footprint_20mdash_20ready_20to_20use_20with_20bootstrap_20and_20foundation_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20view_20the_20collection_20a_13',['sibling of a href https: github com iconic open iconic iconic a it is a hyper legible collection of 223 icons with a tiny footprint mdash ready to use with bootstrap and foundation a href https: github com iconic open iconic view the collection a',['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md14',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;'],['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md0',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;']]],
  ['source_20sibling_20of_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20iconic_20a_20it_20is_20a_20hyper_20legible_20collection_20of_20223_20icons_20with_20a_20tiny_20footprint_20mdash_20ready_20to_20use_20with_20bootstrap_20and_20foundation_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20view_20the_20collection_20a_14',['source sibling of a href https: github com iconic open iconic iconic a it is a hyper legible collection of 223 icons with a tiny footprint mdash ready to use with bootstrap and foundation a href https: github com iconic open iconic view the collection a',['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md14',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;'],['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md0',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;']]],
  ['sprite_15',['sprite',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md6',1,'Using Open Iconic&apos;s SVG Sprite'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md20',1,'Using Open Iconic&apos;s SVG Sprite']]],
  ['started_16',['started',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md2',1,'Getting Started'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md16',1,'Getting Started']]],
  ['started_20with_20open_20iconic_20check_20out_20our_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20icons_20a_20and_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20reference_20a_20sections_17',['started with open iconic check out our a href https: github com iconic open iconic icons a and a href https: github com iconic open iconic reference a sections',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md3',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md17',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.']]],
  ['svg_20sprite_18',['svg sprite',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md6',1,'Using Open Iconic&apos;s SVG Sprite'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md20',1,'Using Open Iconic&apos;s SVG Sprite']]],
  ['svgs_19',['svgs',['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md19',1,'Using Open Iconic&apos;s SVGs'],['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md5',1,'Using Open Iconic&apos;s SVGs']]]
];
