var searchData=
[
  ['webapi_0',['WebAPI',['../namespace_web_a_p_i.html',1,'']]],
  ['webapi_2eassemblyinfo_2ecs_1',['WebAPI.AssemblyInfo.cs',['../_web_a_p_i_8_assembly_info_8cs.html',1,'']]],
  ['webapi_2eglobalusings_2eg_2ecs_2',['WebAPI.GlobalUsings.g.cs',['../_web_a_p_i_8_global_usings_8g_8cs.html',1,'']]],
  ['webapi_2emvcapplicationpartsassemblyinfo_2ecs_3',['WebAPI.MvcApplicationPartsAssemblyInfo.cs',['../_web_a_p_i_8_mvc_application_parts_assembly_info_8cs.html',1,'']]],
  ['webapi_3a_3acontrollers_4',['Controllers',['../namespace_web_a_p_i_1_1_controllers.html',1,'WebAPI']]],
  ['webapi_3a_3aservices_5',['Services',['../namespace_web_a_p_i_1_1_services.html',1,'WebAPI']]],
  ['what_20s_20in_20open_20iconic_6',['what s in open iconic',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md1',1,'What&apos;s in Open Iconic?'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md15',1,'What&apos;s in Open Iconic?']]],
  ['with_20a_20tiny_20footprint_20mdash_20ready_20to_20use_20with_20bootstrap_20and_20foundation_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20view_20the_20collection_20a_7',['with a tiny footprint mdash ready to use with bootstrap and foundation a href https: github com iconic open iconic view the collection a',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md0',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md14',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;']]],
  ['with_20open_20iconic_20check_20out_20our_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20icons_20a_20and_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20reference_20a_20sections_8',['with open iconic check out our a href https: github com iconic open iconic icons a and a href https: github com iconic open iconic reference a sections',['../md__blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md3',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.'],['../md_folder_2_blazor_wasm_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md17',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.']]]
];
